runtime: java23
env: flex
handlers:
  - url: /.*
    script: this field is required, but ignored
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
resources:
  cpu: 1
  memory_gb: 1.0
  disk_size_gb: 10
env_variables:
  SPRING_DATASOURCE_URL: "jdbc:mysql://sql10.freesqldatabase.com:3306/sql10776253?useSSL=false&serverTimezone=UTC"
  SPRING_DATASOURCE_USERNAME: "sql10776253"
  SPRING_DATASOURCE_PASSWORD: "pU8EjG1m3h"