runtime: java21
instance_class: F1
handlers:
  - url: /.*
    script: auto
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 1
env_variables:
  SPRING_DATASOURCE_URL: "jdbc:mysql://sql10.freesqldatabase.com:3306/sql10776253?useSSL=false&serverTimezone=UTC"
  SPRING_DATASOURCE_USERNAME: "sql10776253"
  SPRING_DATASOURCE_PASSWORD: "pU8EjG1m3h"